// Generated by CoffeeScript 1.6.3
(function() {
  var You2MeApp;

  You2MeApp = (function() {
    You2MeApp.prototype.inited = false;

    You2MeApp.prototype.pageTexts = "";

    You2MeApp.prototype.$cacheResult = null;

    You2MeApp.prototype.$cacheResult_new = null;

    You2MeApp.prototype.$cacheResult_src = null;

    You2MeApp.prototype.htmlCover = '<div style="z-index #fff; position: fixed; top:0; left:0; width: 100%;height: 100%; background:#f1c40f; color:#fff; display: table; font-family: AppleGothic, sans-serif; vertical-align: center; text-align: center; font-size: 4em;"><p style="display: table-cell; width:100%; height: 100%; vertical-align: middle">☞ きみ</p></div>';

    You2MeApp.prototype.htmlLogo = '<div style=" z-index #fff; position: fixed; top: 0;right:0; padding: 10px; background:#f1c40f; color:#fff; font-family: AppleGothic, sans-serif;">☞ きみ</div>';

    You2MeApp.prototype.reg = /私|ワタシ|わたし|わたくし|ワタクシ|あたし|アタシ|僕|ボク|ぼく|おれ|オレ|俺|嫁|ヨメ|わたくし|わし|あたい|わい|わて|わだす|あだす|わす|おいら|オイラ|おら|オラ|せっしゃ|拙者/g;

    function You2MeApp() {
      var $cover, $logo, changesString, cssHilight,
        _this = this;
      if (window.You2MeAppInited) {
        alert("一度実行済みです。ページを再読み込みしてください。");
        return;
      }
      window.You2MeAppInited = true;
      console.log("You2MeApp Start!");
      changesString = function(much) {
        return "<hgwspan class='u2m-hit'><hgwspan class='src'>" + much + "</hgwspan><hgwspan class='new'>きみ</hgwspan></hgwspan>";
      };
      this.pageTexts = $('body').html();
      $('body').html(this.pageTexts.replace(this.reg, changesString));
      $logo = $(this.htmlLogo);
      $cover = $(this.htmlCover);
      $("body").append($cover);
      $("body").append($logo);
      $cover.fadeOut(0).fadeIn(100).delay(1000).fadeOut(2000);
      this.$cacheResult = $(".u2m-hit");
      this.$cacheResult_new = this.$cacheResult.find(".new");
      this.$cacheResult_src = this.$cacheResult.find(".src");
      this.$cacheResult_new.hide();
      this.$cacheResult.data("src-visible", false);
      cssHilight = {
        "color": "#e74c3c",
        "cursor": "pointer"
      };
      this.$cacheResult_new.show();
      this.$cacheResult_src.hide();
      this.$cacheResult.css(cssHilight);
      $(document).on("click", ".u2m-hit", function(e) {
        var $current;
        $current = $(e.currentTarget);
        if (!$current.data("src-visible")) {
          $current.find(".new").hide();
          $current.find(".src").show();
          $current.data("src-visible", true);
        } else {
          $current.find(".new").show();
          $current.find(".src").hide();
          $current.data("src-visible", false);
        }
        e.preventDefault();
        return false;
      });
    }

    return You2MeApp;

  })();

  $(function() {
    return new You2MeApp();
  });

}).call(this);

/*
//@ sourceMappingURL=app.map
*/
